image:
  file: .github/dockerfiles/Dockerfile.ubuntu-base
  context: .github
tasks:
  - name: Initial setup
    init: sh scripts/init.sh
  - name: Server
    init: gp sync-await setup
    command: ./target/debug/app 
  - name: Frontend-TS
    init: gp sync-await setup
    command: yarn run dev
  # Optionally, do both at once.
  # - name: Tauri dev
  #   init: gp sync-await setup
  #   command: yarn run tauri dev

vscode:
  extensions:
    - matklad.rust-analyzer
    - serayuzgur.crates
    - bungcip.better-toml