FROM gitpod/workspace-full
ARG TAURI_DEPS="libwebkit2gtk-4.0-dev \
    build-essential \
    curl \
    wget \
    libssl-dev \
    libgtk-3-dev \
    libappindicator3-dev \
    librsvg2-dev"

RUN sudo DEBIAN_FRONTEND=noninteractive apt-get update 
RUN sudo DEBIAN_FRONTEND=noninteractive apt-get install -qy ${TAURI_DEPS}
